spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #url: jdbc:mysql://localhost:3306/walletpicpay_db
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/walletpicpay_db
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true

  #Mocky que trará
  #o retorno das requisições

client:
  authorization:
    service:
      url: "https://run.mocky.io/v3/c75e6afe-bd8c-4e64-a5c1-b1141fc31ae5"
notification:
  authorization:
    service:
      url: "https://run.mocky.io/v3/cf4a0fef-c5c0-49b0-9915-4fd68abaa8f2"